controllers:
    resource: ../src/Controller/
    type: attribute

nova_pessoa:
    path: /pessoas
    controller: App\Controller\PessoaController::novo
    methods:
        - POST

pessoas:
    path: /pessoas
    controller: App\Controller\PessoaController::buscarTodos
    methods:
        - GET

pessoa:
    path: /pessoas/{id}
    controller: App\Controller\PessoaController::buscarUsuario
    methods:
        - GET

atualiza_pessoa:
    path: /pessoas/{id}
    controller: App\Controller\PessoaController::atualizar
    methods:
        - PUT

remove_pessoa:
    path: /pessoas/{id}
    controller: App\Controller\PessoaController::remove
    methods:
        - DELETE

nova_loja:
    path: /lojas
    controller: App\Controller\LojaController::novo
    methods:
        - POST

lojas:
    path: /lojas
    controller: App\Controller\LojaController::buscarTodos
    methods:
        - GET

loja:
    path: /lojas/{id}
    controller: App\Controller\LojaController::buscarUsuario
    methods:
        - GET

atualiza_loja:
    path: /lojas/{id}
    controller: App\Controller\LojaController::atualizar
    methods:
        - PUT

remove_loja:
    path: /lojas/{id}
    controller: App\Controller\LojaController::remove
    methods:
        - DELETE